name: zMenu
version: '1.0.0.0'
main: fr.maxlego08.menu.MenuPlugin
description: Inventory management plugin
author: Maxlego08
website: https://groupez.dev
api-version: '1.19'
contributors: [ mani1232 ]

folia-supported: true

dependencies:
  - name: HeadDatabase
    required: false
    bootstrap: true
  - name: PlaceholderAPI
    required: true
    bootstrap: true
  - name: zTranslator
    required: false
    bootstrap: true