name: zMenu
authors: [ Maxlego08 ]
main: fr.maxlego08.menu.MenuPlugin
description: Inventory management plugin
website: https://groupez.dev/resources/zmenu.253
version: BETA-1.0.0.5
api-version: 1.13
contributors: [ mani1232 ]
softdepend:
- HeadDatabase
- PlaceholderAPI
- zTranslator

folia-supported: true